{{- range $item := .Values.providerConfigs.cloudfoundryBtpOrchestrateCloud}}
  {{- if and ($item) (ne $item.providerConfigRefName "")}}
---
apiVersion: cloudfoundry.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{required "A valid value is required! (.Values.providerConfigs.cloudfoundryBtpOrchestrateCloud[].providerConfigRefName)" $item.providerConfigRefName | lower | quote}}
  labels:
    openmcp.cloud/blueprint-building-block: "{{ $.Chart.Name }}"
    openmcp.cloud/blueprint-building-block-version: "{{ $.Chart.Version }}"
spec:
  endpoint:
    {{- required "A valid value is required! (.Values.providerConfigs.cloudfoundryBtpOrchestrateCloud[].endpoint)" $item.endpoint | toYaml | nindent 4 }}
  credentials:
    {{- required "A valid value is required! (.Values.providerConfigs.cloudfoundryBtpOrchestrateCloud[].credentials)" $item.credentials | toYaml | nindent 4 }}
  {{- end }}
{{- end }}