---
apiVersion: v2
name: sap-btp-services
description: A Helm Chart to create dynamically SAP BTP Services instances and bindings.
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.9
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.2.0"
# A list of URLs to source code for this project (optional)
sources:
  - https://github.com/openmcp-project/blueprint-building-blocks
  - "https://github.com/SAP/sap-btp-service-operator"
# A SemVer range of compatible Kubernetes versions (optional)
kubeVersion: ">=1.20.0"
# Whether this chart is deprecated (optional, boolean)
deprecated: false
# The URL of this projects home page (optional)
home: ""
icon: "https://www.sap.com/content/dam/application/shared/logos/partner/powering-sap-btp-color-logo.svg"
