name: Tag modified Helm Chart

on:
  workflow_call: {}

permissions:
  contents: write # to be able to publish a GitHub release      
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  git-tag-modified-helm-chart:
    name: Tag modified Helm Chart
    runs-on: [solinas]    
    steps:
    - uses: openmcp-project/blueprint-building-blocks/.github/actions/git-tag-modified-helm-chart@main      